name: Terraform

on:
  push:
    branches: [ "master" ]
  workflow_run:
    workflows: ["Build and Push to GAR"]
    types:
      - completed

env:
  TF_IN_AUTOMATION: "true"
  TF_VAR_app_version: "0.0.0"
  TF_VAR_region: ${{ vars.GCP_REGION }}
  TF_VAR_project: ${{ vars.GCP_PROJECT_ID }}
  TF_VAR_repository: ${{ vars.GCP_PROJECT_ID }}
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get latest tag
        run: echo "TF_VAR_app_version=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
