name: Build and Push to Artifact Registry

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Get short SHA"
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: "Authenticate with Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          project_id: "${{ vars.GCP_PROJECT_ID }}"
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Configure Docker"
        run: |-
            gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet
            if ! gcloud artifacts repositories describe ${{ vars.GCP_REPOSITORY }} --location=${{ vars.GCP_REGION }} --project=${{ vars.GCP_PROJECT_ID }}; then
              gcloud artifacts repositories create ${{ vars.GCP_REPOSITORY }} --location=${{ vars.GCP_REGION }} --repository-format=docker --project=${{ vars.GCP_PROJECT_ID }}
            fi
      
      - name: "Set GAR_LOCATION"
        run: |-
          echo "GAR_LOCATION=${{ vars.GCP_REGION }}-docker.pkg.dev/\
          ${{ vars.GCP_PROJECT_ID }}/\
          ${{ vars.GCP_REPOSITORY }}/\
          ${{ vars.SERVICE_APP }}:${{ env.SHORT_SHA }}" >> $GITHUB_ENV

      - name: "Push image"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.GAR_LOCATION }}